### ISSUE TITLE
Please add minLength to options

### ISSUE THREAD

**Issue by martonx** [nescalante/bonanza#9]
If term minimal length is greater or equal then options.minLength then the search should start. I don't want to query my server backend all the time, when somebody write less then 3 characters into the search box.

**Comment by nescalante** [comment]
Hi @martonx, I added a fix to support this:

```
bonanza(document.querySelector('input'), options, function (query, done) {
  if (query.search.length > 3) {
    request
      .get('/search?term=' + query.search + '&offset=' + query.offset + '&limit=' + query.limit)
      .on('response', function (res) {
        done(null, res.body);
      })
      .on('error', function (err) {
        done(err);
      });
  } else {
    done();
  }
});
```

I think that will work for you

**Comment by martonx** [comment]
Hi @nescalante 

Yes, this was my idea too, to handle this situation, just I think the elegant solution is to have an option parameter for handling this in bonanza.
